require: rubocop-rails

Layout/LineLength:
  Max: 90

Metrics/MethodLength:
  Max: 20

Style/FrozenStringLiteralComment:
  Enabled: true
  SafeAutoCorrect: true

Style/Documentation:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false
